kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zeus.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "update"]