apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zeus.fullname" . }}
  labels:
    {{- include "zeus.labels" . | nindent 4 }}
data:
  schedules: |
    {{- with .Values.config }}
      {{- toYaml . | nindent 4 }}
    {{- end }}