kind: ConfigMap
metadata:
  name: {{ include "zeus.fullname" . }}
  labels:
    {{- include "zeus.labels" . | nindent 4 }}
data:
  schedules: |
    # schedules:
    # - name: change-key-aws
    #   cron: "*/1 * * * *"
    #   usernameOnAws: nimtechnology
    #   namespaceOnK8s: default
    #   accessKeyOnK8s:
    #     name: secret-aws
    #     key: accesskey
    #   secretKeyOnK8s:
    #     name: secret-aws
    #     key: secretkey
    #   restartWorkloads:
    #     - kind: deployment
    #       name: "argo-workflow-argo-workflows-server"